In [3]:
from tensorflow.keras.preprocessing.text import one_hot
text = [
"Deep learning is a subset of machine learning", 
"Neural networks are a key component of deep learning",
"Supervised learning involves training a model on labeled data",
"Unsupervised learning finds patterns in data without labels",
"Reinforcement learning is based on rewards and punishments",
"Transfer learning allows models to leverage pre-trained knowledge"
]
    

In [4]:
# Define vocabulary size
vocab_size = 1000
# One-hot encode the text
onehot_repr = [one_hot(words, vocab_size) for words in text]
print(onehot_repr)


[[342, 194, 489, 559, 236, 578, 626, 194], [985, 811, 865, 559, 177, 749, 578, 342, 194], [511, 194, 771, 800, 559, 46, 660, 130, 303], [183, 194, 186, 851, 706, 303, 1, 75], [585, 194, 489, 743, 660, 136, 29, 596], [8, 194, 386, 645, 528, 724, 291, 46, 777]]


In [6]:
# Small sentcess for testing
sentences = [
    "I love machine learning",
    "I love deep learning",
    "Machine learning is fun",
    "Deep learning is fascinating",
    "Neural networks are powerful",
    "Keras makes building models easy"
]
# One-hot encode the test sentences
test_onehot = [one_hot(words, vocab_size) for words in sentences]
test_onehot

[[966, 227, 626, 194],
 [966, 227, 342, 194],
 [626, 194, 489, 504],
 [342, 194, 489, 475],
 [985, 811, 865, 948],
 [662, 365, 187, 645, 221]]

In [7]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential



In [8]:
# Define embedding parameters
embedding_vector_features = 40
max_length = 10
# Pad the sequences to ensure uniform input size
embedded_docs = pad_sequences(onehot_repr, maxlen=max_length, padding='pre')
print(embedded_docs)

[[  0   0 342 194 489 559 236 578 626 194]
 [  0 985 811 865 559 177 749 578 342 194]
 [  0 511 194 771 800 559  46 660 130 303]
 [  0   0 183 194 186 851 706 303   1  75]
 [  0   0 585 194 489 743 660 136  29 596]
 [  0   8 194 386 645 528 724 291  46 777]]


In [10]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length=max_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[ 0.04085955, -0.00650885, -0.0337347 ,  0.02015624,  0.04374831,
         0.01932217, -0.01682113,  0.00903745, -0.01712758, -0.01383976,
         0.02878686,  0.04850774,  0.03497646,  0.04919532,  0.04388291,
        -0.03471887,  0.02767109, -0.02223736, -0.02858779,  0.04045634,
         0.01914651,  0.04859788, -0.04721096,  0.00412831, -0.03574838,
         0.02958072, -0.04116786, -0.03419014, -0.04401296, -0.00739042,
        -0.03014123, -0.00412093,  0.04937177,  0.04400686, -0.04071405,
         0.03592919, -0.02224927, -0.00727474, -0.00771062, -0.03736547],
       [ 0.04085955, -0.00650885, -0.0337347 ,  0.02015624,  0.04374831,
         0.01932217, -0.01682113,  0.00903745, -0.01712758, -0.01383976,
         0.02878686,  0.04850774,  0.03497646,  0.04919532,  0.04388291,
        -0.03471887,  0.02767109, -0.02223736, -0.02858779,  0.04045634,
         0.01914651,  0.04859788, -0.04721096,  0.00412831, -0.03574838,
         0.02958072, -0.04116786, -0.03419014, -0.

In [15]:
!pip install tensorflow-gpu --user

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Raj Kalash Tiwari\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Raj Kalash Tiwari\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Raj Kalash Tiwari\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^

In [2]:
import tensorflow as tf

# This command lists all physical devices TensorFlow can see
devices = tf.config.list_physical_devices('GPU')
print("TensorFlow GPU check:", devices)
if len(devices) > 0:
    print(f"🚀 Success! Found {len(devices)} GPU(s):")
    for device in devices:
        print(f"  - {device}")
else:
    print("⚠️ GPU not found. TensorFlow is stuck with the CPU.")
    print("Check your NVIDIA driver, CUDA, and cuDNN setup. Good luck.")
tf.test.is_built_with_cuda()

TensorFlow GPU check: []
⚠️ GPU not found. TensorFlow is stuck with the CPU.
Check your NVIDIA driver, CUDA, and cuDNN setup. Good luck.


False

In [3]:
import torch
if torch.cuda.is_available():
    print(f"🚀 Success! Found {torch.cuda.device_count()} GPU(s):")
    for i in range(torch.cuda.device_count()):
        print(f"  - {torch.cuda.get_device_name(i)}")

🚀 Success! Found 1 GPU(s):
  - NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [4]:
!python3 -m pip install 'tensorflow[and-cuda]'
# Verify the installation:
!python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\Raj Kalash Tiwari\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: "'tensorflow[and-cuda]'": Expected package name at the start of dependency specifier
    'tensorflow[and-cuda]'
    ^
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'


In [5]:
!python3 -m pip install tensorflow[and-cuda]
# Verify the installation:
!python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-2.20.0-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached protobuf-6.33.0-cp310-abi3-win_amd64.whl.metadata (593 bytes)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached grpcio-1.76.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
  Using cached keras-3.12.0-py3-none-any.whl.metadata (5.9 kB)
  Using cached h5py-3.15.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
  Using cached nvidia_cublas_cu12-12.9.1.4-py3-none-win_amd64.whl.metadata (1.

ERROR: Cannot install tensorflow[and-cuda]==2.16.1, tensorflow[and-cuda]==2.16.2, tensorflow[and-cuda]==2.17.0, tensorflow[and-cuda]==2.17.1, tensorflow[and-cuda]==2.18.0, tensorflow[and-cuda]==2.18.1, tensorflow[and-cuda]==2.19.0, tensorflow[and-cuda]==2.19.1 and tensorflow[and-cuda]==2.20.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'


In [8]:
import tensorflow as tf
driver= tf.config.list_physical_devices('GPU')


In [9]:
# Define strategy
strategy = tf.distribute.MirroredStrategy()

print(f'Number of devices: {strategy.num_replicas_in_sync}')

# Create model within strategy scope
with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(128, activation='relu', input_shape=(784,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
Number of devices: 1


c:\Users\Raj Kalash Tiwari\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
# Check which device operations are running on
tf.debugging.set_log_device_placement(True)

# Create a tensor and check device placement
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)

print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [12]:
import tensorflow as tf
import numpy as np

# Enable memory growth for GPUs
gpus = tf.config.experimental.list_physical_devices('GPU')
print("GPUs found: ", gpus)
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)

# Create synthetic data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(-1, 784).astype('float32') / 255.0
x_test = x_test.reshape(-1, 784).astype('float32') / 255.0

# Use multi-GPU strategy if available
if len(tf.config.experimental.list_physical_devices('GPU')) > 1:
    strategy = tf.distribute.MirroredStrategy()
else:
    strategy = tf.distribute.get_strategy()

with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(512, activation='relu', input_shape=(784,)),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train,
                    batch_size=256,
                    epochs=10,
                    validation_data=(x_test, y_test))

GPUs found:  []
Epoch 1/10


c:\Users\Raj Kalash Tiwari\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9047 - loss: 0.3229 - val_accuracy: 0.9607 - val_loss: 0.1304
Epoch 2/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9632 - loss: 0.1213 - val_accuracy: 0.9736 - val_loss: 0.0870
Epoch 3/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9741 - loss: 0.0827 - val_accuracy: 0.9776 - val_loss: 0.0749
Epoch 4/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9797 - loss: 0.0638 - val_accuracy: 0.9799 - val_loss: 0.0646
Epoch 5/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9843 - loss: 0.0501 - val_accuracy: 0.9806 - val_loss: 0.0618
Epoch 6/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9859 - loss: 0.0433 - val_accuracy: 0.9819 - val_loss: 0.0608
Epoch 7/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9887 - loss: 0.0355 - val_accuracy: 0.9812 - val_loss: 0.0654
Epoch 8/10
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9902 - loss: 0.0300 - val_accuracy: 0.9814 - val_

In [13]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

# Check what devices are available
print("\nAvailable devices:")
for device in tf.config.list_physical_devices():
    print(f" - {device}")

# Specifically check for GPUs
gpus = tf.config.list_physical_devices('GPU')
print(f"\nNumber of GPUs detected: {len(gpus)}")
if gpus:
    for gpu in gpus:
        print(f"GPU: {gpu}")

TensorFlow version: 2.20.0

Available devices:
 - PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')

Number of GPUs detected: 0


In [ ]:
# Uninstall current version and install with CUDA support
!pip uninstall tensorflow
!pip install tensorflow[and-cuda]

^C


In [2]:


print("Using optimized CPU configuration")

Using optimized CPU configuration
